
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PGHOST'] || 'localhost' %>
  username: <%= ENV['PGUSER'] || 'postgres' %>
  password: <%= ENV['PGPASS'] || '' %>
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tbk_tech_assessment_development

test:
  <<: *default
  database: tbk_tech_assessment_test

production:
  <<: *default
  database: tbk_tech_assessment_production

